<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Lua language for TIC-80</string>
	<key>fileTypes</key>
	<array>
		<string>lua</string>
	</array>
	<key>name</key>
	<string>TIC-80 lua</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#general</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>bracket-index-self</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=self)(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.self.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.language.self.lua</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
			</array>
		</dict>
		<key>comment-block</key>
		<dict>
			<key>begin</key>
			<string>--\[(=*)\[</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]\1\]</string>
			<key>name</key>
			<string>comment.block.lua</string>
		</dict>
		<key>comment-line</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lua</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(--)(?!\[\[).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-dash.lua</string>
		</dict>
		<key>function-call</key>
		<dict>
			<key>begin</key>
			<string>(?:(\.?\w+)|(?&lt;=self))(?:(?:(\.\w[\w\.]*))*)[\.:](\w+)(?:\s*\(|(?=['"]))|(\w+)(?:\s*\(|(?=['"]))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.object.lua</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.object.nested.lua</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>meta.call.method.other.lua</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>meta.call.function.other.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)|(?&lt;=['"])</string>
			<key>name</key>
			<string>meta.functioncall.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
			</array>
		</dict>
		<key>function-definition</key>
		<dict>
			<key>begin</key>
			<string>\b(function)\s?([a-zA-Z_.:]+[.:])?([a-zA-Z_]\w*)?\s*(\()([^)]*)(\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.lua</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.scope.lua</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.lua</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.lua</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.lua</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\bend\b</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
			</array>
		</dict>
		<key>general</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tic-api</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-multiline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment-line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lua-constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lua-self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lua-keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lua-logic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lua-operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lua-function-require</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lua-function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function-call</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#table</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bracket-index-self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable-index</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
			</array>
		</dict>
		<key>lua-constant</key>
		<dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(false|nil|true|_G|_VERSION|math\.(pi|huge))\b|(?&lt;![.])\.{3}(?!\.)</string>
			<key>name</key>
			<string>constant.language.lua</string>
		</dict>
		<key>lua-function</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;![^.]\.|:)\b(assert|collectgarbage|dofile|error|getfenv|getmetatable|ipairs|loadfile|loadstring|module|next|pairs|pcall|print|rawequal|rawget|rawset|select|setfenv|setmetatable|tonumber|tostring|type|unpack|xpcall|coroutine\.(create|resume|running|status|wrap|yield)|string\.(byte|char|dump|find|format|gmatch|gsub|len|lower|match|rep|reverse|sub|upper)|table\.(concat|insert|maxn|remove|sort)|math\.(abs|acos|asin|atan2?|ceil|cosh?|deg|exp|floor|fmod|frexp|ldexp|log|log10|max|min|modf|pow|rad|random|randomseed|sinh?|sqrt|tanh?|ult|type|tointeger)|io\.(close|flush|input|lines|open|output|popen|read|tmpfile|type|write)|os\.(clock|date|difftime|execute|exit|getenv|remove|rename|setlocale|time|tmpname)|package\.(cpath|loaded|loadlib|path|preload|seeall)|debug\.(debug|[gs]etfenv|[gs]ethook|getinfo|[gs]etlocal|[gs]etmetatable|getregistry|[gs]etupvalue|traceback))\b(?=[ ]*[({])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.functioncall.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
			</array>
		</dict>
		<key>lua-function-require</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.lua</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.lua</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:require (["'][^"']+["']))|(?:require\(([^\)]+)\))</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<key>lua-keyword</key>
		<dict>
			<key>match</key>
			<string>\b(break|do|else|for|if|elseif|return|then|repeat|while|until|end|function|local|in)\b</string>
			<key>name</key>
			<string>keyword.control.lua</string>
		</dict>
		<key>lua-logic</key>
		<dict>
			<key>match</key>
			<string>\b(and|or|not)\b</string>
			<key>name</key>
			<string>keyword.operator.lua</string>
		</dict>
		<key>lua-operator</key>
		<dict>
			<key>match</key>
			<string>\+|-|%|#|\*|\/|\^|==?|~=|&lt;=?|&gt;=?|(?&lt;!\.)\.{2}(?!\.)</string>
			<key>name</key>
			<string>keyword.operator.lua</string>
		</dict>
		<key>lua-self</key>
		<dict>
			<key>match</key>
			<string>(?&lt;![^.]\.|:)\b(self)\b</string>
			<key>name</key>
			<string>variable.language.self.lua</string>
		</dict>
		<key>numeric-constant</key>
		<dict>
			<key>match</key>
			<string>(?&lt;![\d.])\s0x[a-fA-F\d]+|\b\d+(\.\d+)?([eE]-?\d+)?|\.\d+([eE]-?\d+)?</string>
			<key>name</key>
			<string>constant.numeric.lua</string>
		</dict>
		<key>string-double</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.lua</string>
				</dict>
			</array>
		</dict>
		<key>string-multiline</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!--)\[(=*)\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]\1\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.other.multiline.lua</string>
		</dict>
		<key>string-single</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.lua</string>
				</dict>
			</array>
		</dict>
		<key>table</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.tabledecl.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
			</array>
		</dict>
		<key>tic-api</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;![^.]\.|:)\b(TIC|scanline|btn|btnp|mouse|print|font|trace|spr|map|mset|mget|pix|line|circ|circb|rect|rectb|tri|cls|peek|poke|peek4|poke4|memcpy|memset|pmem|sfx|time)\b(?=[ ]*[({])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.functioncall.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.object.lua</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.object.nested.lua</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:(\.?\w[\w\d]*+)\.(?:(?:(\w[\w\d\.]*)\.)*+)(\w[\w\d]*+)|(\.?\w[\w\d]*+))</string>
			<key>name</key>
			<string>variable.other.lua</string>
		</dict>
		<key>variable-index</key>
		<dict>
			<key>begin</key>
			<string>((\.?\w[\w\d]*+)?\.(?:(?:(\w[\w\d\.]*+)\.?)*+)|(\w[\w\d]*+))(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.lua</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.object.lua</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.object.nested.lua</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.object.lua</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>meta.structure.key.lua</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.structure.key.lua</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.arrayindex.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.lua</string>
	<key>uuid</key>
	<string>adf0c904-8baa-40e9-837b-17758d42d0ce</string>
</dict>
</plist>
